# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://pseudosmp.com"
baseurl: ""
siteIcon: /media/android-chrome-192x192.png
siteYear: 2021
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: The Pseudo Force SMP
serverDescription: Fun Cross-Platform Survival Multiplayer!
serverIP: play.pseudosmp.com
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://pseudosmp.com/discord
discordServerID: 842779800694947840
discordChannelID: 846311576725356615

# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
   - name: About
     url: about
   - name: Vote
     url: vote
   - name: Guide
     url: guide
     newtab: true
   - name: Discord
     url: discord
     newtab: true

# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
